apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-secret-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: argo-cd
  source:
    path: apps/aws-secret-operator
    repoURL: https://github.com/github-amine-kherbouche/argocd-poc.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
